Update README.md
elbb/elbb-dev-environment pull request #26
Opened 2021-05-19 11:27 UTC by JanZachmann

2021-05-20 06:44 UTC, JoergZeidler requested changes

2021-05-20 06:44 UTC, JoergZeidler commented on README.md
>  # (e)mbedded (l)inux (b)uilding (b)locks - local development environment
in general, we should remove the "local" info of all environment

2021-05-20 06:44 UTC, JoergZeidler commented on README.md
> +./dobi.sh dev-environment-concourse-start ?????
the "dev-environemt-" prefix of all commands should be removed in the readme

2021-05-20 06:44 UTC, JoergZeidler commented on README.md
> +You can start the local "Artifactory Community Edition for C/C++" from the root directory via
maybe the info that "start from root directory" should be in a general section available

2021-05-20 07:07 UTC, JanZachmann commented on README.md
>  # (e)mbedded (l)inux (b)uilding (b)locks - local development environment
done

2021-05-20 07:07 UTC, JanZachmann commented on README.md
> +./dobi.sh dev-environment-concourse-start ?????
done

2021-05-20 07:07 UTC, JanZachmann commented on README.md
> +You can start the local "Artifactory Community Edition for C/C++" from the root directory via
done

2021-05-20 14:50 UTC, JoergZeidler requested changes

2021-05-20 14:50 UTC, JoergZeidler commented on README.md
> +## Local Concourse CI environment
I had meant in my previous comment that the term "local" could be removed from the document in its entire context, as we use these environments on a server, for example.

2021-05-20 18:41 UTC, JanZachmann commented on README.md
> +## Local Concourse CI environment
I know. There are 31 occurrences of the word "local" in the readme. I'm not sure if it is correct to remove them all. Feel free to remove the ones you think that can be removed.

2021-05-25 06:33 UTC, JoergZeidler commented on README.md
> +## Local Concourse CI environment
We should leave it as it is.

2021-05-25 06:33 UTC, JoergZeidler approved these changes

2021-05-25 06:37 UTC, merged